import Logo from './Logo.png';
import DNI from './dni.svg';
import Paciente from './doctor-bag-svgrepo-com.svg';
import Apple from './icons8-apple.svg';
import Facebook from './icons8-facebook.svg';
import Google from './icons8-google.svg';
import Mail from './icons8-mail-50.png';
import PadLock from './icons8-padlock.svg';
import User from './user-svg.svg';
import Verify from './verify-key.svg';

export {Logo};
export {DNI};
export {Paciente};
export {Apple};
export {Facebook};
export {Google};
export {Mail};
export {PadLock};
export {User};
export {Verify};